name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npx playwright install
    - run: npm install -D @playwright/test
    - run: npm start & sleep 5
    - run: node server/server.js & sleep 5
    - run: npx playwright test tests/ui.test.js
 
 
