name: LibraryCatalog CI/CD
 
on:
  push:
    branches:
      - "main"
 
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
      name: Checkout repo
 
    - uses: actions/setup-node@v3
      name: Use Node.js 18.x
      with:
        node-version: 18.x
        cache: 'npm'
 
    - run: npm install
      name: Install dependencies
 
    - run: npm i -g pm2
      name: Install pm 2
 
    - run: pm2 start server/server.js
      name: Start API server
 
    - name: Install playwright browsers
      run: npx playwright install --with-deps
 
    - name: Run tests
      run: npx playwright test
 
    - name: Stop server
      run: pm2 stop server
 
 
 
 
